### ISSUE TITLE
Uncaught TypeError:  is not a function

### ISSUE THREAD

**Issue by jimmyxu** [bangumi/scripts#14]
`Uncaught TypeError:  is not a function `[`VM2197:310`](https://github.com/bangumi/scripts/blob/master/upsuper/bilibili_onair.user.js#L301)
`getDateOfLastEp @ VM2197:310`
`isRecentBangumi @ VM2197:321`
`GM_xmlhttpRequest.onload.resp @ VM2197:342`
`(anonymous function) @ VM2133:59`

不过好像底下原来没错的`$prg_list`也开始有问题了…是Chrome坑掉了么？…
Google Chrome	49.0.2573.0 (Official Build) canary （64 ビット）
JavaScript	V8 4.9.52

**Comment by upsuper** [comment]
标明是哪个脚本啦……

**Comment by upsuper** [comment]
唉好麻烦啊……Chrome什么时候能支持`NodeList[@iterator]`啦……
