### ISSUE TITLE
[feature wanted] bgm评分统计功能投票

### ISSUE THREAD

**Issue by chaucerling** [bangumi/scripts#24]
鉴于D娘的 http://netaba.re/ 无法访问，而[部分 bgmer 希望能有直观的评分统计](https://bgm.tv/rakuen/topic/group/341022)，可以考虑用脚本完成这功能。

sai 老板反映的[爬虫/脚本访问过于频繁](http://bgm.tv/user/sai/timeline/status/11742895)，脚本功能可以限定只统计当前用户。

投票用emoji来计数，欢迎大家提出自己的想法

**Comment by upsuper** [comment]
https://github.com/upsuper/bgmrank

我可以把这个做成可执行文件发布，不过只会有命令行版

**Comment by wattlebird** [comment]
No, I think <del>it looked a little better on me</del> ruocaled will soon fix it.

**Comment by chaucerling** [comment]
D娘的网站现在恢复正常了，脚本暂时没必要写了
