### ISSUE TITLE
subjectPowerUp和bangumi-links-domain-fixer.user.js有小冲突

### ISSUE THREAD

**Issue by fireattack** [bangumi/scripts#35]
两者都开启的话，“只看好友”的对勾无法取消：

![image](https://cloud.githubusercontent.com/assets/4130991/24083870/75aacbbc-0cad-11e7-8591-bdde146b891d.png)

**Comment by fireattack** [comment]
@fifth @BinotaLIU

**Comment by fifth** [comment]
因为网页上所有超链接的链接地址被替换了导致我脚本中的某一步报错了
按钮不能取消应该只是诸多副作用中的一个(bgm38)

**Comment by 22earth** [comment]
替换网页的链接效率慢些，还不支持搜索引擎外部访问，建议用链接重定向的扩展： redirector。
使用bgm.tv规则：
Include Patern（from）:
	^https?://(doujin\.)?(?:bangumi|chii)\.(?:tv|in)/(.*$)  
Redirect To（to）:
	https://$1bgm.tv/$2
如果仍然想使用脚本，Firefox可以使用这个脚本  [bangumi_domain_redirector](https://github.com/bangumi/scripts/blob/master/a_little/bangumi_domain_redirector.user.js)
