### ISSUE TITLE
对 Greasemonkey WebExtension ver. 的支持

### ISSUE THREAD

**Issue by ershiwo** [bangumi/scripts#41]
众所周知 Mozilla 早就宣布在 FireFox 57 以后正式启用 WebExtension 代替传统扩展技术，对此 Greasemonkey 刚刚释出了他们的第一个 we 版本的测试版扩展：
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta
目前在 we 版油猴上过去的脚本基本都失效了。而且在新版中部分函数名有变化:
https://github.com/greasemonkey/greasemonkey/issues/2548
https://www.firefox.net.cn/read-54580#read_362468
在扩展完全迁移过去之后应该组织对现有脚本的检查，但是现在不清楚以上情况是暂时的还是既定事实。目前 Nightly 和 Dev 用户建议还是使用 TM 或者 VM 替代。 
@upsuper 谋智那边什么意思啊……

**Comment by fireattack** [comment]
不觉得Mozilla对GM能有什么控制吧…

个人暂时准备换用TM，毕竟Chrome那边一直在用，UI完爆GM/VM，而且最近支持跨浏览器同步了

**Comment by BinotaLIU** [comment]
所以我說那個為什麼會失效……
有沒有新版 GM 的改動列表

**Comment by ershiwo** [comment]
@BinotaLIU https://github.com/greasemonkey/greasemonkey/milestone/74?closed=1 Milestone
@fireattack we 版的油猴外观还行。目前的问题还是架构变化导致部分功能函数在现有的基础上难以实现。

**Comment by BinotaLIU** [comment]
[Greasemonkey 4 For Script Authors](https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html)

有幾個方法不再支持
> As of today, there is no support for: GM_log (use console.log), GM_addStyle, GM_registerMenuCommand, nor GM_getResourceText.

  
其他方法應該是改為 async （返回 `Promises`），並且放到 GM Object 下，
> There is only one object provided to user scripts now, named GM.  It has several properties.  One of them is info – the equivalent of the old GM_info.  There are also several methods of this object: getResourceUrl, deleteValue/getValue/listValues/setValue, xmlHttpRequest.

  
文中也提到可以直接使用 `await`
``` javascript
console.log('Starting the get/set demo ...');
let i = await GM.getValue('i', 0);
console.log(`This time, i was ${i}.`);
GM.setValue('i', i+1);
```
> Here the GM.getValue() method actually returns a promise, but the await keyword transparently converts that to its resolved value, allowing us to write code just as if the value was directly returned – with neither callbacks nor promise resolution.
  
<hr>
  
感覺除了 `addStyle` 以外，大部分的方法都可以兼容吧

**Comment by franklinyu** [comment]
新版 API 有 polyfill

**Comment by BinotaLIU** [comment]
for further discussion or issues with certain script, you're welcome to open new issue.

需要進一步討論或特定腳本的問題，可以開新 Issue。
