### ISSUE TITLE
添加写入权限给 [Liaune]

### ISSUE THREAD

**Issue by Liaune** [bangumi/scripts#42]
怎么没见以前有人写过这个？

**Comment by upsuper** [comment]
https://github.com/bangumi/scripts/issues?q=is%3Aissue+is%3Aclosed+label%3A%E6%B7%BB%E5%8A%A0%E6%9D%83%E9%99%90

**Comment by upsuper** [comment]
邀请已发送

**Comment by Liaune** [comment]
怎么好像没收到？

**Comment by upsuper** [comment]
大概是你邮箱坏掉了，我这里看到是确实已经发了，你也许可以通过Web界面到People里面加入。

**Comment by Liaune** [comment]
收到了，在垃圾箱。。。
