### ISSUE TITLE
bgm-eps-editor.min.user.js批量编辑音乐条目格式错误

### ISSUE THREAD

**Issue by CodeGeassCC** [bangumi/scripts#44]
音乐的应该是

> 光盘编号|曲目编号|原文标题|简体中文标题|时长

但是却显示为

> 章节编号 | 原文标题 | 简体中文标题 | 时长 | 放送日期

**Comment by jokester** [comment]
我寫的時候只試了動畫 (bgm38)  晚點改掉.

還有其他類似錯誤嗎?

**Comment by CodeGeassCC** [comment]
暂时没发现:)

**Comment by jokester** [comment]
改好了 && 改了其他一些bug && 已经发去bgm开发者中心审核
