### ISSUE TITLE
添加黄油助手不能正确抓取人物信息

### ISSUE THREAD

**Issue by chenjiajia9411** [bangumi/scripts#50]
@22earth 
系统：Windows 10 17134.112
浏览器：Firefox 61.0和暴力猴2.9.5 / Chrome 69.0.3462.0和Tampermonkey 4.7.5788
脚本版本：0.3.7

http://www.getchu.com/soft.phtml?id=1007200&gc=gc 中新建角色时不仅不能抓到名字，也不能抓到除了年龄和CV之外的个人信息……
控制台没有报错。
存储中charadata的内容如下（以第一个人物为例）：

> charaData": "{\"characterName\":\"\",\"日文名\":\"\",\"characterIntro\":\"年齢：20歳（大学2年生）\\n身長：156cm　体重：43kg　スリーサイズ：B84/W58/H82\\n血液型：A型　誕生日・星座：4月14日（牡羊座）\\n好き：勉強\\n嫌い：シモネタ（興味がない）\\n\\n主人公の実姉。\\n絵に描いたような優等生として育ち、\\n現在は有名私立に通う女子大生。\\nその真面目な性格からか、\\n浪人生である弟・拓哉のことを快く思っていない。\\n\\nまた、アニメオタクに対して強い嫌悪感を抱いており、\\nそれが引き金となって、弟とのトラブルに発展してしまう。\\n\\nなお、性的なことには一切興味がない模様。\\nセックス自体、不潔だと思っている。\\n\\n「弟がオタクな上に浪人生だなんて、ほんと情けない……」\",\"年齢\":\"20歳（大学2年生）\",\"hiraganaName\":\"かしわぎ ゆか\",\"CV\":\"雪村とあ\",\"characterImg\":\（以下略）

**Comment by 22earth** [comment]
已修复，有些页面的结构变了，我这边改了一下规则。
