### ISSUE TITLE
TypeError: $ is not a function

### ISSUE THREAD

**Issue by jimmyxu** [bangumi/scripts#7]
https://github.com/bangumi/scripts/commit/aab695ef287ab1617ad7aea690debc76eb3116a0#commitcomment-13382709

**Comment by jimmyxu** [comment]
学姐还漏了一个~ https://github.com/bangumi/scripts/blob/685f0f992906ad8ec20ab2a30ba064c75de6c77f/upsuper/bilibili_onair.user.js#L261

**Comment by upsuper** [comment]
啊好麻烦，不想改了……
