### ISSUE TITLE
添加写入权限给 ychz

### ISSUE THREAD

**Issue by oscardoudou** [bangumi/scripts#70]
id : 274591
bangumi主页: https://bangumi.tv/user/ychz
[tampermonkey](https://greasyfork.org/en/scripts/408448-%E7%95%AA%E7%BB%84%E8%AE%A1%E5%88%92-bangumi-%E7%9B%AE%E5%BD%95%E9%A1%B5%E5%A4%9A%E6%A0%87%E7%AD%BE%E7%AD%9B%E9%80%89)
[对应超合金组件](https://bangumi.tv/dev/app/2036)

**Comment by upsuper** [comment]
邀请已发
